name = "OLC CodeJam 2021: Global Temperature Forecast"
default_targets = ["win64", "appimage","lovejs"]
build_directory = "makelove-build"

love_files = [
    "+*",
    "-*/.*",
    "-./makelove-build/*",
]

icon_file = "icon.png"

[lovejs]
memory = "200000000"  # starting memory of the webpage (default is 20 MB)